### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by victoryans003**

### CODE REVIEW

**Comment by faahim** [comment]
Hello @victoryans003 , 

Thanks for checking out the project!
But you don't need to submit a PR on the main repo to be able to host the page with your customizations (which is what I assume you're trying to do.)

I'm gonna close this PR, but please let me know if I can help 🙂

**Comment by victoryans003** [comment]
Hey, sorry. I was just trying to do a "happy birthday thing" to my friend.
I don't know how to use the website, I'm so sorry about that

Em qua, 2 de dez de 2020 02:55, Afiur Rahman Fahim <notifications@github.com>
escreveu:

**Comment by faahim** [comment]
Hi @victoryans003, 

It's no problem at all! 😄  I'm very happy you're giving this a shot and I hope you get to give your friend a pleasant surprise. Feel free to let me know if you need any help with anything! 🙃 

All the best!

**Comment by victoryans003** [comment]
I think it worked. Thank you so much. Here's the link:
https://victoryans003.github.io/happy-birthday-thiago/

I'm so happy it did work 😊 Thanks

Em qua, 2 de dez de 2020 16:19, Afiur Rahman Fahim <notifications@github.com>
escreveu:

**Pull request closed without merging**
